using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;
using System.Linq;
using System.Xml.Linq;
using System.Security;

namespace TSCutter.GUI.Generators
{
    [Generator]
    public class LocalizationSourceGenerator : IIncrementalGenerator
    {
        // 定义一个诊断描述符 (DiagnosticDescriptor)
        // id: 错误代码，方便搜索
        // defaultSeverity: Error 会阻止编译，Warning 只会警告
        private static readonly DiagnosticDescriptor InvalidXmlDescriptor = new DiagnosticDescriptor(
            id: "LOC001",
            title: "Localization XML Parsing Failed",
            messageFormat: "Failed to parse localization file '{0}'. Error: {1}.",
            category: "Localization",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var axamlFiles = context.AdditionalTextsProvider
                .Where(file => file.Path.EndsWith(".axaml"));

            var filesAndContents = axamlFiles.Select((text, token) => 
                (Path: text.Path, Content: text.GetText(token)?.ToString()));

            context.RegisterSourceOutput(filesAndContents, (spc, source) =>
            {
                // 过滤逻辑
                if (!source.Path.Contains("en-US") || string.IsNullOrEmpty(source.Content))
                    return;

                const string className = "LocalizationManager";
                const string namespaceName = "TSCutter.GUI.Utils";

                try
                {
                    // 使用 XDocument 解析
                    var xdoc = XDocument.Parse(source.Content);
                    
                    var resources = xdoc.Root?.Elements()
                        .Select(element => new
                        {
                            Key = element.Attributes().FirstOrDefault(a => a.Name.LocalName == "Key")?.Value,
                            Value = element.Value 
                        })
                        .Where(item => !string.IsNullOrEmpty(item.Key))
                        .ToList();

                    if (resources == null || resources.Count == 0) return;

                    // 构建代码
                    var sb = new StringBuilder();
                    sb.AppendLine($@"// <auto-generated/>
using System;

namespace {namespaceName}
{{
    /// <summary>
    /// 自动生成的本地化管理类
    /// </summary>
    public partial class {className}
    {{");

                    foreach (var item in resources)
                    {
                        // 获取合法的 C# 属性名
                        // String.PleaseLoadVideo -> String_PleaseLoadVideo
                        string propertyName = ToValidIdentifier(item.Key);
                        // 处理 XML 转义和换行，确保 XML 文档注释格式正确
                        string safeValue = SecurityElement.Escape(item.Value)
                                            .Replace("\r", "")
                                            .Replace("\n", " ");
                        
                        // 截断过长的预览文本
                        if (safeValue.Length > 100) safeValue = safeValue.Substring(0, 97) + "...";

                        sb.AppendLine($@"
        /// <summary>
        /// Find localized strings similar to: {safeValue}
        /// </summary>
        public string {propertyName} => this[""{item.Key}""];");
                    }

                    sb.AppendLine(@"    }
}");

                    spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    // 2. 捕获异常并报告给编译器
                    // Location.None 表示这个错误与特定的代码行无关，而是文件级错误
                    var diagnostic = Diagnostic.Create(
                        InvalidXmlDescriptor, 
                        Location.None, 
                        System.IO.Path.GetFileName(source.Path), // {0} 文件名
                        ex.Message); // {1} 具体错误信息

                    spc.ReportDiagnostic(diagnostic);
                }
            });
        }

        /// <summary>
        /// 将任意字符串转换为合法的 C# 标识符
        /// </summary>
        private static string ToValidIdentifier(string key)
        {
            if (string.IsNullOrWhiteSpace(key)) return "InvalidKey";

            // 1. 将点号、空格、减号替换为下划线
            // String.Hello -> String_Hello
            // Login-Btn -> Login_Btn
            var sb = new StringBuilder();
            foreach (char c in key)
            {
                // 将 . - 空格 等替换为 _
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }

            var result = sb.ToString();

            // 2. 如果首字符是数字，前面加个下划线
            // 2ndPlace -> _2ndPlace
            if (char.IsDigit(result[0]))
            {
                result = "_" + result;
            }
            
            return result;
        }
    }
}